import json
import ast
from decimal import Decimal
import time

from sqlalchemy.orm import sessionmaker
from sqlalchemy import text
from sqlalchemy.exc import ProgrammingError
from app.database.connection import engine

from langchain_community.utilities import SQLDatabase
from langchain_openai import OpenAI
from langchain_experimental.sql import SQLDatabaseChain

from app.core.config import DATABASE_URL, OPENAI_API_KEY
from app.core.schemas import QueryRequest

db = SQLDatabase.from_uri(DATABASE_URL)
llm = OpenAI(temperature=0, verbose=True, openai_api_key=OPENAI_API_KEY)

db_chain = SQLDatabaseChain.from_llm(
    llm,
    db,
    verbose=True,
    use_query_checker=True,
    return_intermediate_steps=True
)


def _build_summary_for_no_sql(user_query: str) -> str:
    """
    Сообщение, если цепочка не смогла построить SQL или вопрос явно не про БД.
    """
    return (
        "Я могу отвечать только на вопросы, которые можно решить с помощью SQL-запросов "
        "к базе данных. Похоже, что ваш вопрос:\n\n"
        f"  «{user_query}»\n\n"
        "не связан напрямую с данными в базе. Попробуйте задать вопрос, который опирается "
        "на конкретные данные/таблицы (например: «Сколько заказов за последний месяц?»)."
    )


def _build_summary_for_invalid_sql(user_query: str, sql_query: str, error_text: str) -> str:
    """
    Сообщение, если SQL сгенерирован, но невалидный (ошибка при выполнении).
    """
    return (
        "Не удалось корректно выполнить автоматически сгенерированный SQL-запрос по вашему вопросу.\n\n"
        f"Вопрос: «{user_query}»\n\n"
        f"Сгенерированный SQL:\n{sql_query}\n\n"
        f"Ошибка базы данных: {error_text}\n\n"
        "Попробуйте упростить или переформулировать запрос более явно относительно структуры данных."
    )


def _build_summary_for_empty_result(user_query: str, sql_query: str) -> str:
    """
    Сообщение, если SQL успешен, но данных по запросу нет.
    """
    return (
        "Запрос к базе данных был успешно выполнен, но по вашему вопросу не нашлось подходящих записей.\n\n"
        f"Вопрос: «{user_query}»\n\n"
        f"Использованный SQL-запрос:\n{sql_query}\n\n"
        "Скорее всего, в данных просто нет информации, удовлетворяющей условиям."
    )


def run_full_chain(query_request: QueryRequest) -> dict:
    start_time = time.time()
    print(f"\n[TIMING] --- Chain started ---")

    user_query = query_request.user_query

    # Добавляем инструкцию к вопросу пользователя
    enhanced_user_question = (
        f"{user_query}\n\n"
        "IMPORTANT: Your final answer MUST be in the same language as the original user question above. "
        "If the question cannot be answered using the SQL database (its tables and data), "
        "say explicitly that it cannot be answered using this database."
    )

    try:
        chain_invoke_start = time.time()
        print("[TIMING] Calling LangChain/OpenAI...")
        chain_response = db_chain.invoke(enhanced_user_question)
        chain_invoke_end = time.time()
        print(f"[TIMING] LangChain/OpenAI call took: {chain_invoke_end - chain_invoke_start:.2f} seconds")
    except ProgrammingError as e:
        # Ошибка прямо на этапе работы LangChain/SQLDatabaseChain
        error_text = getattr(e, "orig", e)
        return {
            "sql_query": "Invalid SQL generated by LangChain",
            "result": [],
            "summary": _build_summary_for_invalid_sql(
                user_query=user_query,
                sql_query="(не удалось извлечь SQL, ошибка на этапе генерации/первого выполнения)",
                error_text=str(error_text),
            ),
        }
    except Exception as e:
        # Ловим все остальные возможные ошибки (например, от OpenAI)
        return {
            "sql_query": "Error before SQL generation",
            "result": [],
            "summary": f"Произошла непредвиденная внутренняя ошибка: {str(e)}",
        }

    # ------------------------------------
    sql_query = "SQL query not found."
    raw_result = []

    # Шаг 1: Извлекаем SQL-запрос из ответа LangChain
    # В разных версиях LangChain intermediate_steps могут быть:
    # - списком кортежей (sql, rows)
    # - списком словарей с ключом 'sql_cmd'
    intermediate_steps = chain_response.get("intermediate_steps", [])

    if intermediate_steps:
        for step in intermediate_steps:
            # Вариант 1: словарь
            if isinstance(step, dict) and "sql_cmd" in step:
                sql_query = step["sql_cmd"]
                break
            # Вариант 2: кортеж (sql, result)
            if isinstance(step, (list, tuple)) and len(step) >= 1:
                possible_sql = step[0]
                if isinstance(possible_sql, str) and "SELECT" in possible_sql.upper():
                    sql_query = possible_sql
                    break

    # Если SQL не удалось извлечь — предполагаем, что вопрос не про БД
    if sql_query == "SQL query not found.":
        total_end_time = time.time()
        print(f"[TIMING] Total chain execution took: {total_end_time - start_time:.2f} seconds")
        print("[TIMING] --- Chain finished (no SQL) ---\n")
        return {
            "sql_query": None,
            "result": [],
            "summary": _build_summary_for_no_sql(user_query),
        }

    # Дополнительная защита: допустим только SELECT-запросы
    if "SELECT" not in sql_query.upper():
        total_end_time = time.time()
        print(f"[TIMING] Total chain execution took: {total_end_time - start_time:.2f} seconds")
        print("[TIMING] --- Chain finished (non-SELECT SQL) ---\n")
        return {
            "sql_query": sql_query.replace("\n", " ").strip(),
            "result": [],
            "summary": (
                "Я могу выполнять только безопасные SELECT-запросы к базе данных. "
                "Сгенерированный запрос не является SELECT. Попробуйте переформулировать вопрос."
            ),
        }

    # Шаг 2: Выполняем найденный SELECT-запрос ещё раз, чтобы получить чистый результат
    try:
        db_exec_start = time.time()
        print("[TIMING] Re-executing SQL query against local DB...")
        Session = sessionmaker(bind=engine)
        with Session() as session:
            result_proxy = session.execute(text(sql_query))
            column_names = result_proxy.keys()

            raw_result = [
                {
                    key: (float(value) if isinstance(value, Decimal) else value)
                    for key, value in zip(column_names, row)
                }
                for row in result_proxy.fetchall()
            ]
        db_exec_end = time.time()
        print(f"[TIMING] Local DB execution took: {db_exec_end - db_exec_start:.2f} seconds")
    except ProgrammingError as e:
        error_text = getattr(e, "orig", e)
        total_end_time = time.time()
        print(f"[TIMING] Total chain execution took: {total_end_time - start_time:.2f} seconds")
        print("[TIMING] --- Chain finished (ProgrammingError on re-exec) ---\n")
        return {
            "sql_query": sql_query.replace("\n", " ").strip(),
            "result": [],
            "summary": _build_summary_for_invalid_sql(
                user_query=user_query,
                sql_query=sql_query,
                error_text=str(error_text),
            ),
        }
    except Exception as e:
        total_end_time = time.time()
        print(f"[TIMING] Total chain execution took: {total_end_time - start_time:.2f} seconds")
        print("[TIMING] --- Chain finished (generic error on re-exec) ---\n")
        return {
            "sql_query": sql_query.replace("\n", " ").strip(),
            "result": [],
            "summary": f"Ошибка при повторном выполнении SQL-запроса: {str(e)}",
        }

    total_end_time = time.time()
    print(f"[TIMING] Total chain execution took: {total_end_time - start_time:.2f} seconds")
    print("[TIMING] --- Chain finished ---\n")

    # Если данных нет — отдельное человекопонятное сообщение
    if not raw_result:
        return {
            "sql_query": sql_query.replace("\n", " ").strip(),
            "result": [],
            "summary": _build_summary_for_empty_result(user_query, sql_query),
        }

    # Если LangChain всё же сгенерировал текстовый ответ — используем его,
    # но всё равно возвращаем "сырые" данные
    summary_text = str(chain_response.get("result", ""))
    summary_text = summary_text.strip() or "Ответ сгенерирован на основе данных из базы."

    return {
        "sql_query": sql_query.replace("\n", " ").strip(),
        "result": raw_result,
        "summary": summary_text,
    }
